<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Layanan</name>
   <tag></tag>
   <elementGuidId>8c7fbd79-8f8d-4a13-8b5e-1ff7757dc150</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.show.dropdown > #dropdownBasic1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='dropdownBasic1'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>adc55218-1b16-498e-b88b-db0e73395b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fa9e9ad0-63d5-4c16-a1de-08899d6b0a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link language dropdown-toggle landing-text</value>
      <webElementGuid>cde12fd7-28c4-4ee5-91a9-bc75e1b2303b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdownBasic1</value>
      <webElementGuid>ddae4a3a-60e1-4b9f-b6dc-236666c9ebc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>20c271a3-650d-4cef-8e17-a97a8a937c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Layanan</value>
      <webElementGuid>62e40b32-2563-4ff8-a552-25ee56c4a12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarToggler&quot;)/ul[@class=&quot;navbar-nav ml-auto mr-auto&quot;]/li[@class=&quot;nav-item&quot;]/div[@class=&quot;show dropdown&quot;]/a[@id=&quot;dropdownBasic1&quot;]</value>
      <webElementGuid>402bd2d4-24fd-48de-a1e1-7e3096f4045e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='dropdownBasic1'])[3]</value>
      <webElementGuid>28801dfe-65c3-4fba-8716-3d7bd9ad5c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarToggler']/ul/li[6]/div/a</value>
      <webElementGuid>5cf765ac-1df0-45c1-9727-aa33c2a81a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Layanan')]</value>
      <webElementGuid>8c2eb1d7-93d4-46ae-bd65-4be35787b199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Mutu'])[1]/following::a[1]</value>
      <webElementGuid>912e9311-af27-44eb-b660-5ea741cf7e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temukan Kami'])[1]/following::a[2]</value>
      <webElementGuid>826a7883-ee64-4246-89ef-ee7d2d2853c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regular'])[1]/preceding::a[1]</value>
      <webElementGuid>9b7a7468-05d8-4463-b02e-df6f17f069e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next Day'])[1]/preceding::a[2]</value>
      <webElementGuid>19f4f4a5-4990-49f2-b826-e6fa6be9ea6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Layanan']/parent::*</value>
      <webElementGuid>862e8bd1-bb3f-471f-a334-06e5e1dcf357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/a</value>
      <webElementGuid>c691ecb9-8e1a-444b-a586-57cfef696801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'dropdownBasic1' and (text() = 'Layanan' or . = 'Layanan')]</value>
      <webElementGuid>172259b9-faac-4e75-878a-2a2eb293e86d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
