<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DropDown_Option_CekOngkir</name>
   <tag></tag>
   <elementGuidId>bfa8d6c1-0460-42d3-97a2-c8798da5c07c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarToggler']/ul/li[6]/div/div/a[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a85a5f86-35f1-41ca-b6bb-9fe1430f78fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>451412ae-f80f-4d52-bd67-e7d8753651f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cek-ongkir</value>
      <webElementGuid>441b2d8c-7120-414e-beb9-1c2ddf204707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cek Ongkir</value>
      <webElementGuid>5b740540-4f4d-4893-8a15-98d0ac2a3ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarToggler&quot;)/ul[@class=&quot;navbar-nav ml-auto mr-auto&quot;]/li[@class=&quot;nav-item&quot;]/div[@class=&quot;show dropdown&quot;]/div[@class=&quot;dropdown-danger dropdown-menu-right dropdown-menu show&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>6f039409-307d-46a0-b7b1-fedd442fe918</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarToggler']/ul/li[6]/div/div/a[4]</value>
      <webElementGuid>51372cc4-5a6b-458b-bad0-6db9d0c1d27f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cek Ongkir')]</value>
      <webElementGuid>429c9b8b-879d-4eb1-8084-4b1b60a57ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Same Day'])[1]/following::a[1]</value>
      <webElementGuid>8f6d24ca-8820-4fc0-958d-f2920237d2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next Day'])[1]/following::a[2]</value>
      <webElementGuid>4bb3fd33-7414-43de-82a1-60b28a0e0947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[1]/preceding::a[1]</value>
      <webElementGuid>8a228f75-ed49-4e65-9816-ca3e1d81f950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Karir'])[1]/preceding::a[2]</value>
      <webElementGuid>0353d359-f1bb-4f6d-9673-d11cab8a23cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cek Ongkir']/parent::*</value>
      <webElementGuid>a7384b52-3737-4c7c-87bd-e5184ea9dad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cek-ongkir')]</value>
      <webElementGuid>48ec76eb-232f-4afe-af65-4215493ccab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/div/a[4]</value>
      <webElementGuid>ea3d9c51-8745-4c90-b6a0-139c1dfe8e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cek-ongkir' and (text() = 'Cek Ongkir' or . = 'Cek Ongkir')]</value>
      <webElementGuid>cb16100a-88d2-413d-b81f-e3ce400aff74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
